spring.application.name=Contact Manager
server.port=8081

# ******** mySql database configurations ********
# data source url, localhost : server ip address where db is running, here it is running on our machine so localhost,
# protocol : jdbc, db : sql, 3306 : db port no. (can be change when db will run server), scm20 : db name inside db, 
spring.datasource.url=jdbc:mysql://localhost:3306/cm_002
spring.datasource.username=root
spring.datasource.password=sanya002

# ******** JPA configurations ************
# to see query on console
spring.jpa.show-sql=true
# for creating schemas and tables
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
# dialect tells JPA that for which db(mysql or postgres) it have to make query -> NOT Required bcz
# we've added the jar file and driver of our DB(mysql)
## spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect


# ******** E-mail configurations ************



# ******** Security configurations ************

# spring.security.user.name=sanya
# spring.security.user.password=sanya

# ******** OAuth2 client configurations ************
# GGOGLE configure
# spring.security.oauth2.client.registration.google.client-name=google
spring.security.oauth2.client.registration.google.client-id=1093014475281-i47vldqmnv911e70vl04feb51qhqb4m1.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
# scopes means what details of yours users can see
spring.security.oauth2.client.registration.google.scope=email,profile
# spring.security.oauth2.client.registration.google.authorization-grant-type=authorization

# GITHUB configure
# spring.security.oauth2.client.registration.GITHUB.client-name=github
spring.security.oauth2.client.registration.GITHUB.client-id=Iv23lipVpgbut5Sip9Db
spring.security.oauth2.client.registration.GITHUB.client-secret=3f11e5670724bcb3904a40945fc9dd9ba4b2a99e
spring.security.oauth2.client.registration.GITHUB.scope=email,profile

# CLOUDINARY configurations
cloudinary.cloud.name=dltvrzpdr
cloudinary.api.key=832361318964329
cloudinary.api.secret=F04sxV75ym8XX4ToO4hf0_8FUPw
